# Generated by Django 3.0.1 on 2019-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='tag name')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='registered_time')),
            ],
            options={
                'verbose_name': '패스트캠퍼스 태그',
                'verbose_name_plural': '패스트캠퍼스 태그',
                'db_table': 'fastcampus_tag',
            },
        ),
    ]
