# Generated by Django 3.0.1 on 2019-12-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20191219_1035'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='fastcampus_fcuser',
        ),
    ]
