# Generated by Django 3.0.1 on 2019-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0004_auto_20191219_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시'),
        ),
    ]
