# Generated by Django 3.0.1 on 2019-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0005_auto_20191219_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일시'),
        ),
    ]
